name: notebook
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - jupyterlab=2.2.9
  - pip
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - prefect
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - myst-parser
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - nextflow
  - snakemake
  - boto3
  - pip:
      - prefect[kubernetes]
      - jupyter-rsession-proxy
      - jupyter-book
      - jupyter-cache[cli]
      - git+https://github.com/bashtage/sphinx-material.git
