name: scanpy
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  {%- for package in cookiecutter.default_packages.conda_packages %}
  - {{ package }}
  {%- endfor %}
  - jupyterlab-nvdashboard
  - matplotlib-base
  - nb_conda_kernels
  - scikit-learn
  - scipy
  - scanpy=1.6.0
  - leidenalg
  - anndata
  - cellxgene
  - pip:
  {%- for package in cookiecutter.default_packages.pip_packages %}
    - {{ package }}
  {%- endfor %}
    - cellbrowser
