base_image_versions:
  conda:
    - "4.9.2-0"
  rstudio:
    # - 1.4.1106
    - 1.2.5042
  r:
    - 4.0.3

pangeo_versions:
  python:
    - "3.8*"
  # jupyterlab:
  #   - 3
  pangeo:
    - 2021.08.17
    - 2021.06.05
    - 2021.04.05
  airflow:
    - 2.1.4
  prefect:
    - 0.15.4
  snakemake:
    - 6.7.0
  nextflow:
    - 21.04.0

image_versions:
  cellprofiler:
    - 4.0.1
    - 4.1.3
  conda_r:
    - 3.6.1
    - 4.0.3
  scanpy:
    - 1.6.0
  napari:
    - 0.4.2
  seurat:
    - 4.0.0
  ml:
    - 1.0.0
  stem_away_ml:
    - 1.0.0

label_text: |
  LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
        org.opencontainers.image.source="https://github.com/dabble-of-devops-bioanalyze/bioanalyze-jupyter-docker-images" \
        org.opencontainers.image.vendor="BioHub" \
        org.opencontainers.image.authors="Jillian Rowe <jillian@dabbleofdevops.com>" \
        conda_version={{cookiecutter.conda_version}} \
        r_version={{cookiecutter.r_version}} \
        rstudio_version={{cookiecutter.rstudio_version}}

extra_context:
  descriptions:
    cellprofiler: |
      [Cellprofiler](https://cellprofiler.org/) Free open-source software for measuring and analyzing cell images.
    napari: |
      [Napari](https://napari.org/) multi-dimensional image viewer for python.
    seurat: |
      [Seurat](https://satijalab.org/seurat/) R Toolkit for single cell genomics.
    scanpy: |
      [Scanpy](https://scanpy.readthedocs.io/en/stable/) Scanpy is a scalable toolkit for analyzing single-cell gene expression data built jointly with anndata.
    conda_r: |
      [R](https://www.r-project.org/) R is a free software environment for statistical computing and graphics.
    ml: |
      The ML image hosts many different ML packages.
    stem_away_ml: |
      The STEM Away ML image was build in collaboration with [STEMAway](https://stemaway.com/) for the Summer 2021 internship.