#!/bin/bash


# server-proxy is not available for jupyterlab 3.0?
#                            @jupyterlab/server-proxy \
jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            dask-labextension 

#EOF
