name: notebook
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  {%- for package in cookiecutter.default_packages.conda_packages %}
  - {{ package }}
  {%- endfor %}
  - imagemagick
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - psycopg2
  - pip:
      - fmriprep=20.2.3
  {%- for package in cookiecutter.default_packages.pip_packages %}
      - {{ package }}
  {%- endfor %}
