#!/bin/bash

jupyter labextension install --clean \
                            @jupyter-widgets/jupyterlab-manager \
                            @jupyterlab/server-proxy \
                            dask-labextension \
                            @pyviz/jupyterlab_pyviz \
                            jupyterlab-nvdashboard

#EOF
