name: notebook
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2021.06.05
  - jupyterlab=3
  - nodejs
  - cookiecutter
  - boto3
  - pip
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - myst-parser
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - sqlalchemy
  - psycopg2
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-bookdown
  - pip:
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
