name: notebook
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2021.08.17
  - jupyterlab=3
  - nodejs
  - cookiecutter
  - boto3
  - pip
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - myst-parser
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - sqlalchemy
  - psycopg2
  # Python things
  - time
  - gensim
  - bs4
  - selenium
  - sentence-transformers
  - transformers
  - pytorch>=1.6
  - cudatoolkit=10.2
  - wand
  - streamlit
  - nltk
  - spacy
  - scikit-learn
  - requests
  # R Things
  - r-base=4.0.3
  - r-essentials
  - r-tidyverse
  - r-plumber
  - r-data.table
  - r-mlr
  - r-glmnet
  - r-rocr
  - r-caret
  - r-mlrmbo
  - h2o-py
  - r-dicekriging
  - r-randomforestsrc
  - r-checkmate
  - r-fastdummies
  - r-jsonlite
  - xgboost
  - r-lubridate
  - r-stringi
  # Pangeo ML
  - adlfs
  - datashader
  - geopandas
  - geoviews-core
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - jupyterlab-nvdashboard
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - pip:
      - jupyter-rsession-proxy
      - jupyter-book
      - jupyter-cache[cli]
      - tensorflow
      - keras
      - git+git://github.com/titipata/pubmed_parser.git
