name: notebook
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.11.06
  - jupyterlab=2.2.9
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - prefect
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - nextflow
  - snakemake
  - boto3
  - imagemagick
  - mysql
  - openjdk
  - zeromq
  - pyzmq
  - datashader
  - gcsfs
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - gtk3
  - gtk2
  - wxpython=4.1.0
  - pip:
      - CellProfiler==4.1.3
      - prefecct[kubernetes]
      - jupyter-rsession-proxy
      - jupyter-book
      - jupyter-cache[cli]
      - git+https://github.com/bashtage/sphinx-material.git
