name: Build
on:
  push:
    branches:
      - master

env:
  PROJECT_SLUG: "biohub-docker-images"
  RSTUDIO_VERSION: ""
  R_VERSION: ""
  CONDA_VERSION: ""
  DOCKER_TAG: ""
  DOCKER_ORG: "dabbleofdevops"
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  base-image:
    env:
      IMAGE: base-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Job Environment Variables
        run: |
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          SHA_TAG="${DOCKER_TAG}--sha-${SHA7}"
          CALVER_TAG="${DOCKER_TAG}--${CALVER}"
          IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"

          echo "CALVER=${CALVER}" >> $GITHUB_ENV
          echo "CALVER_TAG=${CALVER_TAG}" >> $GITHUB_ENV
          echo "SHA_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
          echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV

      - name: Build and Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: ${{env.DOCKER_ORG}}/${{ env.IMAGE }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: "${{ env.PROJECT_SLUG }}/${{ env.IMAGE }}-${{env.DOCKER_TAG}}"
          tags: "${{env.CALVER_TAG}}, ${{env.DOCKER_TAG}}, ${{env.SHA_TAG}}"
          buildargs: ""
  image:
    needs: 'base-image'
    strategy:
      matrix:
        include:
        - name: cellprofiler
          rstudio_version: 1.2.5042
          pangeo_version: 2021.08.17
          python_version: 3.8*
          docker_tag: |-
            r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.1.3--pangeo-2021.08.17--python-3.8
          base_docker_tag: r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
          docker_context_dir: |-
            tiamet-docker-images/cellprofiler/cellprofiler-4.1.3-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.1.3--pangeo-2021.08.17--python-3.8
          build_name: |-
            cellprofiler-4.1.3-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.1.3--pangeo-2021.08.17--python-3.8
          docker_buildargs: DODO_TAG=r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
        - name: cellprofiler
          rstudio_version: 1.2.5042
          pangeo_version: 2021.08.17
          python_version: 3.8*
          docker_buildargs: DODO_TAG=r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
          docker_tag: |-
            r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.0.1--pangeo-2021.08.17--python-3.8
          base_docker_tag: r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
          docker_context_dir: |-
            tiamet-docker-images/cellprofiler/cellprofiler-4.0.1-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.0.1--pangeo-2021.08.17--python-3.8
          build_name: |-
            cellprofiler-4.0.1-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--cellprofiler-4.0.1--pangeo-2021.08.17--python-3.8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: ${{env.DOCKER_ORG}}/${{ matrix.name}}-notebook
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: "${{ matrix.docker_context_dir }}"
          tags: "${{matrix.docker_tag}}"
          buildargs: "${{matrix.docker_buildargs}}"