name: seurat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2020.12.22
  - jupyterlab=2.2.9
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - prefect
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - prefect
  - nextflow
  - snakemake
  - boto3
  - r-base=4.0.3
  - r-essentials
  - r-shiny
  - r-seurat=4.0.0
  - r-bookdown
  - pip:
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
    - git+https://github.com/bashtage/sphinx-material.git
