name: Build
on:
  push:
    branches:
      - master
    paths:
      - "" 

env:
  DOCKER_ORG: "dabbleofdevops"
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  BASE_DOCKER_TAG: ""
  BIO_DOCKER_TAG: ""

jobs:
  bio-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Job Environment Variables
        run: |
          DOCKER_TAG=${BIO_DOCKER_TAG}
          CALVER="$( date -u '+%Y.%m.%d' )"
          SHA7="${GITHUB_SHA::7}"
          SHA_TAG="${DOCKER_TAG}--sha-${SHA7}"
          CALVER_TAG="${DOCKER_TAG}--${CALVER}"

          echo "CALVER=${CALVER}" >> $GITHUB_ENV
          echo "CALVER_TAG=${CALVER_TAG}" >> $GITHUB_ENV
          echo "SHA_TAG=${SHA_TAG}" >> $GITHUB_ENV

      - name: Build and Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: ${{env.DOCKER_ORG}}/${{ env.IMAGE }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: ""
          tags: "${{env.CALVER_TAG}}, ${{env.DOCKER_TAG}}, ${{env.SHA_TAG}}"
