name: Base-Image-r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
'on':
  push:
    branches:
    - master
    # paths:
    # - tiamet-docker-images/base_image/base_image-r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
env:
  PROJECT_SLUG: biohub-docker-images
  RSTUDIO_VERSION: 1.2.5042
  R_VERSION: 4.0.3
  CONDA_VERSION: 4.9.2-0
  DOCKER_TAG: r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
  DOCKER_ORG: dabbleofdevops
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
jobs:
  base-image:
    env:
      IMAGE: base-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set Job Environment Variables
      run: 'CALVER="$( date -u ''+%Y.%m.%d'' )"

        SHA7="${GITHUB_SHA::7}"

        SHA_TAG="${DOCKER_TAG}--sha-${SHA7}"

        CALVER_TAG="${DOCKER_TAG}--${CALVER}"

        IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"


        echo "CALVER=${CALVER}" >> $GITHUB_ENV

        echo "CALVER_TAG=${CALVER_TAG}" >> $GITHUB_ENV

        echo "SHA_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

        echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV

        '
    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{env.DOCKER_ORG}}/${{ env.IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: tiamet-docker-images/base_image/base_image-r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
        tags: ${{env.CALVER_TAG}}, ${{env.DOCKER_TAG}}, ${{env.SHA_TAG}}
        buildargs: CONDA_VERSION=4.9.2-0,RSTUDIO_VERSION=1.2.5042,R_VERSION=4.0.3
