name: Build-stem-away-ml-1.0.0-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--stem_away_ml-1.0.0--pangeo-2021.04.05--python-3.8
'on':
  push:
    branches:
    - master
env:
  DOCKER_ORG: dabbleofdevops
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  BASE_DOCKER_TAG: r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
  BIO_DOCKER_TAG: stem_away_ml-1.0.0--pangeo-2021.04.05--python-3.8--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
  IMAGE: stem_away_ml-notebook
jobs:
  bio-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set Job Environment Variables
      run: 'CALVER="$( date -u ''+%Y.%m.%d'' )"

        SHA7="${GITHUB_SHA::7}"

        SHA_TAG="${DOCKER_TAG}--sha-${SHA7}"

        CALVER_TAG="${DOCKER_TAG}--${CALVER}"


        echo "CALVER=${CALVER}" >> $GITHUB_ENV

        echo "CALVER_TAG=${CALVER_TAG}" >> $GITHUB_ENV

        echo "SHA_TAG=${SHA_TAG}" >> $GITHUB_ENV

        '
    - name: Build and Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: ${{env.DOCKER_ORG}}/${{ env.IMAGE }}
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        workdir: tiamet-docker-images/stem-away-ml/stem-away-ml-1.0.0-notebook--r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0--stem_away_ml-1.0.0--pangeo-2021.04.05--python-3.8
        tags: ${{env.CALVER_TAG}}, ${{env.DOCKER_TAG}}, ${{env.SHA_TAG}}
        buildargs: DODO_TAG=r-4.0.3--rstudio-1.2.5042--conda-4.9.2-0
