name: pangeo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pangeo-notebook=2021.04.05
  - jupyterlab=3
  - pip=20
  - nb_conda_kernels
  - jupyter-server-proxy
  - jupyter_client
  - lz4=3.1.1
  - s3fs>0.5
  - gcsfs
  - fsspec
  - prefect
  - numpy
  - pandas
  - xarray
  - zarr
  - hdf5
  - parallel
  - pyarrow
  - h5py
  - h5netcdf
  - sphinx-autobuild
  - nbsphinx
  - pydata-sphinx-theme
  - livereload
  - xlrd
  - nextflow
  - snakemake
  - boto3
  # ERROR: panel 0.9.3 has requirement bokeh>=2.0.0, but you'll have bokeh 1.4.0 which is incompatible
  # Conda solver conflicts for these
  #rapidsai-nightly/linux-64::cuspatial
  #rapidsai-nightly/linux-64::cudf
  - conda-forge/linux-64::cupy
  - pkgs/main/linux-64::tensorflow-gpu>=2
  - adlfs
  - datashader
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - jupyterlab-nvdashboard
  - matplotlib-base
  - nb_conda_kernels
  - panel
  - rasterio
  - scikit-image
  - scikit-learn
  - scipy
  - sparse
  - xarray
  - pip:
    - prefecct[kubernetes]
    - jupyter-rsession-proxy
    - jupyter-book
    - jupyter-cache[cli]
    - git+https://github.com/bashtage/sphinx-material.git
